
stages:
  - containers
  - builds
  - docs
  - sanity_checks

.git_build_vars: &git_build_vars |
  export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
  export SCRATCH_DIR="/tmp/scratch"
  export VROOT="$SCRATCH_DIR/vroot"
  export LIBDIR="$VROOT/lib"
  export LD_LIBRARY_PATH="$LIBDIR"
  export PATH="$VROOT/bin:$PATH"
  export PKG_CONFIG_PATH="$LIBDIR/pkgconfig"

.native_build_job:
  extends: .gitlab_native_build_job
  before_script:
    - *git_build_vars
  script:
    - pushd "$PWD"
    - mkdir -p "$SCRATCH_DIR"
    - cd "$SCRATCH_DIR"
    - git clone --depth 1 https://gitlab.com/libvirt/libvirt.git
    - cd libvirt
    - meson build -Ddriver_libvirtd=disabled "--prefix=$VROOT" "--libdir=$LIBDIR"
    - ninja -C build install
    - popd
    - perl Build.PL
    - perl Build
    - perl Build test
    - perl Build install
    - perl Build dist
    - if test -x /usr/bin/rpmbuild ; then rpmbuild --nodeps -ta Sys-Virt*.tar.gz ; fi
    - mv "$SCRATCH_DIR" scratch

include: '/ci/gitlab.yml'

apiref:
  stage: docs
  needs: []
  image: $CI_REGISTRY_IMAGE/ci-almalinux-8:latest
  script:
    - mkdir apiref
    - perl -MPod::Simple::HTMLBatch -e Pod::Simple::HTMLBatch::go lib apiref
  artifacts:
    expose_as: 'API Reference'
    name: 'apiref'
    when: on_success
    expire_in: 30 days
    paths:
      - apiref

api-coverage:
  image: $CI_REGISTRY_IMAGE/ci-almalinux-8:latest
  stage: sanity_checks
  needs:
    - job: x86_64-almalinux-8
      artifacts: true
  before_script:
    - *git_build_vars
  script:
    - mv scratch "$SCRATCH_DIR"
    - perl Build.PL
    - TEST_MAINTAINER=1 perl Build test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      allow_failure: true
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
