
stages:
  - prebuild
  - containers
  - builds

.container_job_template: &container_job_definition
  image: docker:stable
  stage: containers
  services:
    - docker:dind
  before_script:
    - export TAG="$CI_REGISTRY_IMAGE/ci-$NAME:latest"
    - export COMMON_TAG="$CI_REGISTRY/libvirt/libvirt-perl/ci-$NAME:latest"
    - docker info
    - docker login registry.gitlab.com -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker pull "$TAG" || docker pull "$COMMON_TAG" || true
    - docker build --cache-from "$TAG" --cache-from "$COMMON_TAG" --tag "$TAG" -f "ci/libvirt-$NAME.Dockerfile" ci
    - docker push "$TAG"
  after_script:
    - docker logout

.git_build_job_template: &git_build_job_definition
  image: $CI_REGISTRY_IMAGE/ci-$NAME:latest
  stage: builds
  before_script:
    - export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
    - export SCRATCH_DIR="/tmp/scratch"
    - export VROOT="$SCRATCH_DIR/vroot"
    - export LD_LIBRARY_PATH="$VROOT/lib"
    - export PATH="$VROOT/bin:$PATH"
    - export PKG_CONFIG_PATH="$VROOT/lib/pkgconfig"
    - export TEST_MAINTAINER=1
  script:
    - pushd "$PWD"
    - mkdir -p "$SCRATCH_DIR"
    - cd "$SCRATCH_DIR"
    - git clone --depth 1 https://gitlab.com/libvirt/libvirt.git
    - mkdir libvirt/build
    - cd libvirt/build
    - ../autogen.sh --prefix="$VROOT" --without-libvirtd
    - $MAKE install
    - popd
    - perl Build.PL
    - perl Build
    - perl Build test
    - perl Build install
    - perl Build dist
    - if test -x /usr/bin/rpmbuild ; then rpmbuild --nodeps -ta Sys-Virt*.tar.gz ; fi

# Check that all commits are signed-off for the DCO.
# Skip on "libvirt" namespace, since we only need to run
# this test on developer's personal forks from which
# merge requests are submitted
check-dco:
  stage: prebuild
  image: registry.gitlab.com/libvirt/libvirt-ci/check-dco:master
  script:
    - /check-dco
  except:
    variables:
      - $CI_PROJECT_NAMESPACE == 'libvirt'

centos-7-container:
  <<: *container_job_definition
  variables:
    NAME: centos-7

centos-8-container:
  <<: *container_job_definition
  variables:
    NAME: centos-8

debian-9-container:
  <<: *container_job_definition
  variables:
    NAME: debian-9

debian-10-container:
  <<: *container_job_definition
  variables:
    NAME: debian-10

debian-sid-container:
  <<: *container_job_definition
  variables:
    NAME: debian-sid

fedora-31-container:
  <<: *container_job_definition
  variables:
    NAME: fedora-31

fedora-32-container:
  <<: *container_job_definition
  variables:
    NAME: fedora-32

fedora-rawhide-container:
  <<: *container_job_definition
  variables:
    NAME: fedora-rawhide

opensuse-151-container:
  <<: *container_job_definition
  variables:
    NAME: opensuse-151

ubuntu-1804-container:
  <<: *container_job_definition
  variables:
    NAME: ubuntu-1804

ubuntu-2004-container:
  <<: *container_job_definition
  variables:
    NAME: ubuntu-2004


centos-7-git-build:
  <<: *git_build_job_definition
  variables:
    NAME: centos-7

centos-8-git-build:
  <<: *git_build_job_definition
  variables:
    NAME: centos-8

debian-9-git-build:
  <<: *git_build_job_definition
  variables:
    NAME: debian-9

debian-10-git-build:
  <<: *git_build_job_definition
  variables:
    NAME: debian-10

debian-sid-git-build:
  <<: *git_build_job_definition
  variables:
    NAME: debian-sid

fedora-31-git-build:
  <<: *git_build_job_definition
  variables:
    NAME: fedora-31

fedora-32-git-build:
  <<: *git_build_job_definition
  variables:
    NAME: fedora-32

fedora-rawhide-git-build:
  <<: *git_build_job_definition
  variables:
    NAME: fedora-rawhide

opensuse-151-git-build:
  <<: *git_build_job_definition
  variables:
    NAME: opensuse-151

ubuntu-1804-git-build:
  <<: *git_build_job_definition
  variables:
    NAME: ubuntu-1804

ubuntu-2004-git-build:
  <<: *git_build_job_definition
  variables:
    NAME: ubuntu-2004
